#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

ENV_FILE=/home/ckx/quota-dashboard/.deploy-state
OR=/opt/1panel/apps/openresty/openresty
DOMAIN=quota.entropicecho.com
CONF=$OR/conf/conf.d/$DOMAIN.conf

banner "quota-dashboard 上线（DNS + 1Panel 站点 + 证书 + 初始化）"

# ── Stage 1: DNS A 记录 ──────────────────────────────────────────────────
stage "DNS：添加 A 记录"
say "在 DNS 服务商处把 $DOMAIN 指向本机公网 IP。"
say "（参考：cpa.entropicecho.com 已解析到 64.83.29.97，通常用同一 IP。）"
step "打开你的 DNS 服务商控制台，添加记录：类型 A，主机记录 quota，记录值 = 服务器公网 IP。"
ask SERVER_IP "添加完成后，粘贴你填写的服务器公网 IP:"
write_env SERVER_IP "$SERVER_IP"
say "等待解析生效（通常几分钟）。下面本机验证解析结果："
if dig +short "$DOMAIN" 2>/dev/null | grep -qx "$SERVER_IP"; then
  printf '  %s✓%s 解析已生效：%s → %s\n' "$GREEN" "$RESET" "$DOMAIN" "$SERVER_IP"
else
  warn "本机尚未解析到 $SERVER_IP（dig +short $DOMAIN 无匹配）。"
  confirm "仍要继续吗（证书签發需要解析已生效）？" || { say "稍后可重新运行本向导，已保存的值会保留。"; exit 1; }
fi

# ── Stage 2: 1Panel 创建反代网站 ─────────────────────────────────────────
stage "1Panel：创建反向代理网站"
say "1Panel 面板监听在 20399 端口（公网）。用你的入口地址登录。"
step "网站 → 网站列表 → 创建网站 → 类型选「反向代理」。"
step "主域名填：$DOMAIN"
step "代理地址填：http://127.0.0.1:18318"
step "其余保持默认，提交创建。"
pause "创建完成后按 Enter 继续"
if sudo -n test -f "$CONF"; then
  printf '  %s✓%s 检测到站点配置 %s\n' "$GREEN" "$RESET" "$CONF"
else
  warn "未检测到 $CONF"
  confirm "确认网站已创建吗？" || { say "请先完成建站再重新运行。"; exit 1; }
fi

# ── Stage 3: 申请证书 ────────────────────────────────────────────────────
stage "1Panel：申请 Let's Encrypt 证书"
say "为站点签发 HTTPS 证书（HTTP-01 经 80 端口直达 OpenResty，不受 HAProxy 影响）。"
step "网站 → 网站列表 → $DOMAIN → 「证书」。"
step "选择 Let's Encrypt → 申请，勾选自动续期。"
pause "证书签发成功后按 Enter 继续"
if sudo -n test -f "$OR/www/sites/$DOMAIN/ssl/fullchain.pem"; then
  printf '  %s✓%s 检测到证书文件\n' "$GREEN" "$RESET"
else
  warn "未检测到 $OR/www/sites/$DOMAIN/ssl/fullchain.pem"
  confirm "确认证书已签发吗？" || { say "请先完成签发再重新运行。"; exit 1; }
fi

# ── Stage 4: 核对 listen 端口并重载（脚本自动处理）───────────────────────
stage "OpenResty：核对 listen 端口并重载"
say "443 被宿主机 HAProxy 占用（SNI 透传到 8444），站点必须 listen 8444。"
if sudo -n grep -qE 'listen 443' "$CONF"; then
  warn "检测到 listen 443，自动备份并改为 8444 ssl http2"
  sudo -n cp -a "$CONF" "$CONF.bak-$(date +%Y%m%d-%H%M%S)"
  sudo -n sed -i 's/listen 443 ssl http2/listen 8444 ssl http2/; s/listen 443 ssl/listen 8444 ssl http2/' "$CONF"
  printf '  %s✓%s 已改为 8444 并留 .bak 备份\n' "$GREEN" "$RESET"
else
  printf '  %s✓%s listen 端口无需修改\n' "$GREEN" "$RESET"
fi
if sudo -n docker exec 1Panel-openresty-mT7m nginx -t; then
  sudo -n docker exec 1Panel-openresty-mT7m nginx -s reload
  printf '  %s✓%s nginx 配置有效，已 reload\n' "$GREEN" "$RESET"
else
  warn "nginx -t 失败，未 reload。请检查 $CONF 后重跑本向导。"
  exit 1
fi

# ── Stage 5: 上线验证 ────────────────────────────────────────────────────
stage "验证：公网 HTTPS 可达"
say "从本机经公网域名验证（走 HAProxy → OpenResty → 面板完整链路）："
code=$(curl -s -o /dev/null -m 15 -w '%{http_code}' "https://$DOMAIN/" || true)
say "GET https://$DOMAIN/ → HTTP $code"
if [[ "$code" == "200" ]]; then
  printf '  %s✓%s 站点已上线\n' "$GREEN" "$RESET"
else
  warn "预期 200，实际 $code。可先继续初始化，稍后排查（DNS 缓存/证书信任）。"
  confirm "仍要继续初始化吗？" || exit 1
fi

# ── Stage 6: 首次初始化 ─────────────────────────────────────────────────
stage "初始化：主密码 + TOTP + 恢复码"
say "即将在终端交互完成初始化："
step "设置主密码（≥16 位，二次确认，输入不回显）。"
step "抄录 TOTP secret / otpauth URI，在 Authenticator 中添加。"
step "抄录恢复码（只显示一次，离线保存）——它是忘记密码或丢 TOTP 时的唯一恢复途径。"
pause "准备好后按 Enter 开始初始化"
sudo -n docker exec -it quota-dashboard-quota-dashboard-1 node src/server/cli/index.js init
say "初始化完成。现在可以打开网站登录并添加凭证："
open_url "https://$DOMAIN/"
note "添加凭证后建议对照官方页面核对一次额度数字（验收要求）。"

finish
